DELIMITER $$
CREATE TRIGGER duplicateUuidForProtection 
AFTER INSERT ON MYTODO_USER
FOR EACH ROW
BEGIN
IF new.pwd IS NULL THEN
	INSERT INTO MYTODO_PROTECT VALUES(new.uuid, 0);
ELSE
	INSERT INTO MYTODO_PROTECT VALUES(new.uuid, 1);
END IF;
END 
$$
DELIMITER ;



DELIMITER $$
CREATE TRIGGER editBoolForProtection 
AFTER UPDATE ON MYTODO_USER
FOR EACH ROW
BEGIN
IF new.pwd IS NULL THEN
	UPDATE MYTODO_PROTECT SET isProtected = 0 WHERE MYTODO_PROTECT.uuid = new.uuid;
ELSE
	UPDATE MYTODO_PROTECT SET isProtected = 1 WHERE MYTODO_PROTECT.uuid = new.uuid;	
END IF;
END
$$
DELIMITER ;

